version: 2

multi-ecosystem-groups:
  bun-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "bun"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "bun-dependencies"
